# config/config.yaml
server:
  port: "8080"

database:
  host: "localhost"
  port: 5432
  user: "public_config_service"
  password: "public_config_service"
  dbname: "public_config"
  sslmode: "disable"
